//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_pk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string email { get; set; }
        public string size { get; set; }
        public int price { get; set; }
        public Nullable<int> quantity { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string img { get; set; }
        public string gender { get; set; }
        public string location { get; set; }
        public string city { get; set; }
        public string brand { get; set; }
    }
}
