//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_pk
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string email { get; set; }
        public string password { get; set; }
        public string brand { get; set; }
        public string location { get; set; }
        public string city { get; set; }
        public System.DateTime date_register { get; set; }
    }
}
